
2025-02-13 15:49:48,355 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 5, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 420, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:00:28,636 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 5, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 420, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:01:21,205 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 5, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 420, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:02:04,063 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 5, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 420, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:03:39,971 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 5, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 420, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:11:59,392 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 5, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 422, in run
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:19:46,820 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 6, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 424, in run
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:20:41,138 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 6, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 421, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:24:23,539 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 6, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 421, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:29:45,704 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 6, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 421, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:30:23,691 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 6, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 421, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:31:01,155 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 6, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 421, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:38:08,495 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 6, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 421, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:39:30,202 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 6, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 421, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:40:08,253 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 6, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 421, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:40:59,748 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 6, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 421, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:43:13,302 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 6, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 421, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
2025-02-13 16:44:37,635 - ERROR - Uncaught Exception
Traceback (most recent call last):
  File "D:\Huffman-Encoding\main.py", line 6, in <module>
    gui.run()
  File "D:\Huffman-Encoding\gui.py", line 421, in run
    self.root.mainloop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1505, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
